#!/usr/bin/env python3
"""Generate a FreeCAD 1.0.x Python macro from a structured JSON spec.

Usage:
    python3 generate_macro.py spec.json output.FCMacro

Produces a Python macro that, when executed inside FreeCAD (via `freecadcmd
macro.py` or Macro → Macros → Execute), builds a PartDesign Body with a
named feature tree and saves as .FCStd alongside the macro.

Kueipang modeling style (from 27 historical FCStd):
  * PartDesign Body workflow (never Part booleans)
  * Revolution or Pad for base; annular sketch OK (2 concentric circles)
  * PolarPattern for circular repetition
  * Fillet > Chamfer (default Chamfer 0.5-1.0 @ 45°)
  * PartDesign Hole for threaded holes (ISO metric)
  * TechDraw page at end (if `drawing` block present)
"""
import json
import sys
import os
from pathlib import Path


MACRO_PREAMBLE = '''# -*- coding: utf-8 -*-
# Auto-generated by cad-modeling-assistant
# Part: {part_name}
# Description: {description}

import FreeCAD as App
import Part, Sketcher

DOC_NAME = "{part_name}"
doc = App.newDocument(DOC_NAME)
body = doc.addObject("PartDesign::Body", "Body")
doc.recompute()

# ------- Helpers -------

def _axis(axis_name):
    """Resolve 'X'/'Y'/'Z' to origin axis object."""
    target = {{"X": "X_Axis", "Y": "Y_Axis", "Z": "Z_Axis"}}.get(axis_name, "Z_Axis")
    for f in body.Origin.OriginFeatures:
        if f.Name.endswith(target) or target in f.Label:
            return f
    return None

def _plane(plane_name):
    target = {{"XY": "XY_Plane", "XZ": "XZ_Plane", "YZ": "YZ_Plane"}}[plane_name]
    for f in body.Origin.OriginFeatures:
        if f.Name.endswith(target) or target in f.Label:
            return f
    return None

def _make_datum_plane(name, ref_plane, offset_x=0, offset_y=0, offset_z=0,
                       rot_x=0, rot_y=0, rot_z=0):
    """Create a DatumPlane offset from a base origin plane."""
    dp = doc.addObject("PartDesign::Plane", name)
    body.addObject(dp)
    base_plane = _plane(ref_plane)
    if base_plane:
        dp.AttachmentSupport = (base_plane, [""])
        dp.MapMode = "FlatFace"
    dp.AttachmentOffset = App.Placement(
        App.Vector(offset_x, offset_y, offset_z),
        App.Rotation(rot_z, rot_y, rot_x)  # yaw-pitch-roll
    )
    doc.recompute()
    return dp


def _face_ref(tag):
    """Return (feature, 'FaceN') for tag like 'top'/'bottom'/'outer_cyl'/'inner_cyl'."""
    base = body.Tip
    if base is None:
        return None
    try:
        shape = base.Shape
    except Exception:
        return None
    bb = shape.BoundBox
    for i, f in enumerate(shape.Faces):
        try:
            surf_type = f.Surface.TypeId
        except Exception:
            continue
        com = f.CenterOfMass
        if tag == "top" and surf_type == "Part::GeomPlane" and abs(com.z - bb.ZMax) < 0.01:
            return (base, "Face%d" % (i+1))
        if tag == "bottom" and surf_type == "Part::GeomPlane" and abs(com.z - bb.ZMin) < 0.01:
            return (base, "Face%d" % (i+1))
        if tag == "outer_cyl" and surf_type == "Part::GeomCylinder":
            # pick cylindrical face with largest radius
            try:
                r = f.Surface.Radius
                if not hasattr(_face_ref, "_outer_r") or r > _face_ref._outer_r:
                    _face_ref._outer_r = r
                    _face_ref._outer = (base, "Face%d" % (i+1))
            except Exception:
                pass
    if tag == "outer_cyl" and hasattr(_face_ref, "_outer"):
        ref = _face_ref._outer
        del _face_ref._outer, _face_ref._outer_r
        return ref
    return None


def _edges_by_tag(tag):
    """Return list of 'EdgeN' names for the current body.Tip matching tag."""
    base = body.Tip
    shape = base.Shape
    bb = shape.BoundBox
    out = []
    for i, e in enumerate(shape.Edges):
        try:
            curve_id = e.Curve.TypeId
        except Exception:
            continue
        com = e.CenterOfMass
        name = "Edge%d" % (i+1)
        if tag == "top_outer" and curve_id == "Part::GeomCircle" and abs(com.z - bb.ZMax) < 0.01:
            out.append(name)
        elif tag == "bottom_outer" and curve_id == "Part::GeomCircle" and abs(com.z - bb.ZMin) < 0.01:
            out.append(name)
        elif tag == "top" and abs(com.z - bb.ZMax) < 0.01:
            out.append(name)
        elif tag == "bottom" and abs(com.z - bb.ZMin) < 0.01:
            out.append(name)
        elif tag == "all_circles" and curve_id == "Part::GeomCircle":
            out.append(name)
        elif tag == "all":
            out.append(name)
    return out, base


def _make_sketch(name, plane_spec, geometry, constraints=None, face_tag=None):
    sk = doc.addObject("Sketcher::SketchObject", name)
    body.addObject(sk)

    if plane_spec in ("XY", "XZ", "YZ"):
        ref = _plane(plane_spec)
        if ref:
            sk.AttachmentSupport = (ref, [""])
            sk.MapMode = "FlatFace"
    elif plane_spec.startswith("datum:"):
        # Reference a datum plane created earlier by spec
        name = plane_spec.split(":", 1)[1]
        dp = doc.getObject(name)
        if dp:
            sk.AttachmentSupport = (dp, [""])
            sk.MapMode = "FlatFace"
    elif plane_spec.startswith("face:"):
        tag = plane_spec.split(":", 1)[1]
        fref = _face_ref(tag)
        if fref:
            sk.AttachmentSupport = fref
            sk.MapMode = "FlatFace"
        else:
            # Fallback to XY
            ref = _plane("XY")
            if ref:
                sk.AttachmentSupport = (ref, [""])
                sk.MapMode = "FlatFace"
    doc.recompute()

    # Track geometry index → tag for constraint reference
    gidx = []  # list of (type, index)
    for g in geometry:
        t = g["type"]
        if t == "circle":
            c = g["center"]; r = g["radius"]
            circle = Part.Circle(App.Vector(c[0], c[1], 0), App.Vector(0,0,1), r)
            i = sk.addGeometry(circle, False)
            gidx.append(("circle", i))
            # Only auto-constrain to origin if center is (0,0)
            if abs(c[0]) < 1e-6 and abs(c[1]) < 1e-6:
                sk.addConstraint(Sketcher.Constraint("Coincident", i, 3, -1, 1))
            else:
                sk.addConstraint(Sketcher.Constraint("DistanceX", i, 3, c[0]))
                sk.addConstraint(Sketcher.Constraint("DistanceY", i, 3, c[1]))
            sk.addConstraint(Sketcher.Constraint("Diameter", i, 2 * r))
        elif t == "line":
            s, e = g["start"], g["end"]
            line = Part.LineSegment(App.Vector(s[0], s[1], 0), App.Vector(e[0], e[1], 0))
            i = sk.addGeometry(line, False)
            gidx.append(("line", i))
        elif t == "polyline":
            pts = g["points"]
            first_idx = None
            line_indices = []
            for k in range(len(pts) - 1):
                line = Part.LineSegment(App.Vector(pts[k][0], pts[k][1], 0),
                                         App.Vector(pts[k+1][0], pts[k+1][1], 0))
                j = sk.addGeometry(line, False)
                gidx.append(("line", j))
                line_indices.append(j)
            for k in range(len(line_indices) - 1):
                sk.addConstraint(Sketcher.Constraint("Coincident",
                    line_indices[k], 2, line_indices[k+1], 1))
            # Close if first==last
            if len(pts) > 2 and pts[0] == pts[-1]:
                sk.addConstraint(Sketcher.Constraint("Coincident",
                    line_indices[-1], 2, line_indices[0], 1))
        elif t == "rectangle":
            c = g["center"]; w = g["width"]; h = g["height"]
            hx, hy = w/2.0, h/2.0
            corners = [(c[0]-hx, c[1]-hy), (c[0]+hx, c[1]-hy),
                       (c[0]+hx, c[1]+hy), (c[0]-hx, c[1]+hy)]
            lines = []
            for k in range(4):
                a, b = corners[k], corners[(k+1) % 4]
                line = Part.LineSegment(App.Vector(a[0], a[1], 0), App.Vector(b[0], b[1], 0))
                j = sk.addGeometry(line, False)
                lines.append(j); gidx.append(("line", j))
            for k in range(4):
                sk.addConstraint(Sketcher.Constraint("Coincident",
                    lines[k], 2, lines[(k+1) % 4], 1))
            sk.addConstraint(Sketcher.Constraint("Horizontal", lines[0]))
            sk.addConstraint(Sketcher.Constraint("Horizontal", lines[2]))
            sk.addConstraint(Sketcher.Constraint("Vertical", lines[1]))
            sk.addConstraint(Sketcher.Constraint("Vertical", lines[3]))
            # Dimension the width/height
            sk.addConstraint(Sketcher.Constraint("DistanceX", lines[0], 1, lines[0], 2, w))
            sk.addConstraint(Sketcher.Constraint("DistanceY", lines[1], 1, lines[1], 2, h))
            # Fix the center (for positioning)
            sk.addConstraint(Sketcher.Constraint("DistanceX", lines[0], 1, -1, 1, c[0] - hx))
            sk.addConstraint(Sketcher.Constraint("DistanceY", lines[0], 1, -1, 1, c[1] - hy))
        elif t == "point":
            xy = g["xy"]
            pt = Part.Point(App.Vector(xy[0], xy[1], 0))
            i = sk.addGeometry(pt, False)
            gidx.append(("point", i))
            sk.addConstraint(Sketcher.Constraint("DistanceX", i, 1, xy[0]))
            sk.addConstraint(Sketcher.Constraint("DistanceY", i, 1, xy[1]))
        elif t == "arc":
            c = g["center"]; r = g["radius"]
            a0, a1 = g.get("start_angle", 0), g.get("end_angle", 180)
            import math
            arc = Part.ArcOfCircle(Part.Circle(App.Vector(c[0], c[1], 0), App.Vector(0,0,1), r),
                                    math.radians(a0), math.radians(a1))
            i = sk.addGeometry(arc, False)
            gidx.append(("arc", i))

    # Apply explicit constraints if supplied
    if constraints:
        for cn in constraints:
            ctype = cn.get("type", "").capitalize()
            try:
                if ctype in ("Horizontal", "Vertical"):
                    sk.addConstraint(Sketcher.Constraint(ctype, cn["line"]))
                elif ctype in ("Parallel", "Perpendicular", "Equal"):
                    sk.addConstraint(Sketcher.Constraint(ctype, cn["line1"], cn["line2"]))
                elif ctype == "Distance":
                    sk.addConstraint(Sketcher.Constraint("Distance", cn["g1"], cn.get("v1",1),
                                                         cn["g2"], cn.get("v2",1), cn["value"]))
                elif ctype == "Distancex":
                    sk.addConstraint(Sketcher.Constraint("DistanceX", cn["g1"], cn.get("v1",1),
                                                         cn["g2"], cn.get("v2",1), cn["value"]))
                elif ctype == "Distancey":
                    sk.addConstraint(Sketcher.Constraint("DistanceY", cn["g1"], cn.get("v1",1),
                                                         cn["g2"], cn.get("v2",1), cn["value"]))
                elif ctype == "Coincident":
                    p = cn["pts"]
                    sk.addConstraint(Sketcher.Constraint("Coincident", p[0], 1, p[1], 1))
                elif ctype == "Symmetric":
                    sk.addConstraint(Sketcher.Constraint("Symmetric",
                        cn["g1"], cn.get("v1",1), cn["g2"], cn.get("v2",1), cn.get("axis", -2)))
                elif ctype == "Diameter":
                    sk.addConstraint(Sketcher.Constraint("Diameter", cn["circle"], cn["value"]))
                elif ctype == "Radius":
                    sk.addConstraint(Sketcher.Constraint("Radius", cn["circle"], cn["value"]))
            except Exception as e:
                App.Console.PrintMessage("constraint skipped: %s\\n" % e)

    doc.recompute()
    return sk


def _make_pad(sketch, length, midplane=False, reversed=False, name="Pad"):
    pad = doc.addObject("PartDesign::Pad", name)
    body.addObject(pad)
    pad.Profile = sketch
    pad.Length = length
    pad.Midplane = midplane
    pad.Reversed = reversed
    sketch.Visibility = False
    doc.recompute()
    return pad


def _make_pocket(sketch, depth, through_all=False, reversed=False, name="Pocket"):
    pocket = doc.addObject("PartDesign::Pocket", name)
    body.addObject(pocket)
    pocket.Profile = sketch
    if through_all:
        pocket.Type = 1
    else:
        pocket.Length = depth
    pocket.Reversed = reversed
    sketch.Visibility = False
    doc.recompute()
    return pocket


def _make_revolution(sketch, axis_name, angle=360, name="Revolution"):
    rev = doc.addObject("PartDesign::Revolution", name)
    body.addObject(rev)
    rev.Profile = sketch
    ax = _axis(axis_name)
    if ax:
        rev.ReferenceAxis = (ax, [""])
    rev.Angle = angle
    sketch.Visibility = False
    doc.recompute()
    return rev


def _make_polar_pattern(source_features, axis_name, angle, occurrences, name="PolarPattern"):
    pp = doc.addObject("PartDesign::PolarPattern", name)
    body.addObject(pp)
    pp.Originals = source_features
    ax = _axis(axis_name)
    if ax:
        pp.Axis = (ax, [""])
    pp.Angle = angle
    pp.Occurrences = occurrences
    doc.recompute()
    return pp


def _make_linear_pattern(source_features, direction_name, length, occurrences, name="LinearPattern"):
    lp = doc.addObject("PartDesign::LinearPattern", name)
    body.addObject(lp)
    lp.Originals = source_features
    ax = _axis(direction_name)
    if ax:
        lp.Direction = (ax, [""])
    lp.Length = length
    lp.Occurrences = occurrences
    doc.recompute()
    return lp


def _make_mirrored(source_features, plane_name, name="Mirrored"):
    m = doc.addObject("PartDesign::Mirrored", name)
    body.addObject(m)
    m.Originals = source_features
    p = _plane(plane_name)
    if p:
        m.MirrorPlane = (p, [""])
    doc.recompute()
    return m


def _make_fillet(edge_tags, radius, name="Fillet"):
    all_edges = []
    base = None
    for tag in (edge_tags or ["all_circles"]):
        eds, b = _edges_by_tag(tag)
        all_edges.extend(eds); base = b
    all_edges = list(dict.fromkeys(all_edges))
    if not all_edges:
        eds, b = _edges_by_tag("all_circles")
        all_edges = eds; base = b
    if base is None:
        base = body.Tip
    fillet = doc.addObject("PartDesign::Fillet", name)
    fillet.Base = (base, all_edges)
    fillet.Radius = radius
    body.addObject(fillet)
    doc.recompute()
    return fillet


def _make_chamfer(edge_tags, size, angle=45, name="Chamfer"):
    all_edges = []
    base = None
    for tag in (edge_tags or ["all_circles"]):
        eds, b = _edges_by_tag(tag)
        all_edges.extend(eds); base = b
    all_edges = list(dict.fromkeys(all_edges))
    if not all_edges:
        eds, b = _edges_by_tag("all_circles")
        all_edges = eds; base = b
    if base is None:
        base = body.Tip
    ch = doc.addObject("PartDesign::Chamfer", name)
    ch.Base = (base, all_edges)
    ch.Size = size
    body.addObject(ch)
    doc.recompute()
    return ch


def _make_hole(sketch, thread_size, depth, threaded=True, counter_bore=None, counter_sink=None,
               name="Hole"):
    import re
    m = re.match(r"M(\\d+(?:\\.\\d+)?)", thread_size or "M4")
    nominal = float(m.group(1)) if m else 4.0
    tap_drill = nominal * 0.84  # approx tap-drill for coarse thread

    has_circle = any(g.TypeId == "Part::GeomCircle" for g in sketch.Geometry)
    if not has_circle:
        pts = [g for g in sketch.Geometry if g.TypeId == "Part::GeomPoint"]
        for p in pts:
            c = Part.Circle(App.Vector(p.X, p.Y, 0), App.Vector(0,0,1), tap_drill/2.0)
            sketch.addGeometry(c, False)
        doc.recompute()

    hole = doc.addObject("PartDesign::Hole", name)
    body.addObject(hole)
    hole.Profile = sketch
    try:
        hole.ThreadType = "ISOMetricProfile"
        hole.ThreadSize = thread_size
        hole.Threaded = bool(threaded)
    except Exception as e:
        App.Console.PrintMessage("Thread setup skipped: %s\\n" % e)
    hole.Depth = depth
    hole.DepthType = "Dimension"
    if counter_bore:
        try:
            hole.HoleCutType = "Counterbore"
            hole.HoleCutDiameter = counter_bore.get("diameter", nominal * 2)
            hole.HoleCutDepth = counter_bore.get("depth", nominal)
        except Exception:
            pass
    if counter_sink:
        try:
            hole.HoleCutType = "Countersink"
            hole.HoleCutDiameter = counter_sink.get("diameter", nominal * 2)
            hole.HoleCutCountersinkAngle = counter_sink.get("angle", 90)
        except Exception:
            pass
    sketch.Visibility = False
    doc.recompute()
    return hole


# ------- Drawing helpers -------

def _make_techdraw(views=None):
    try:
        import TechDraw
    except Exception:
        return None
    page = doc.addObject("TechDraw::DrawPage", "Page")
    template = doc.addObject("TechDraw::DrawSVGTemplate", "Template")
    import os
    tpl_path = os.path.join(App.getResourceDir(), "Mod", "TechDraw", "Templates",
                             "A4_LandscapeTD.svg")
    if os.path.exists(tpl_path):
        template.Template = tpl_path
    page.Template = template
    vg = doc.addObject("TechDraw::DrawProjGroup", "ProjGroup")
    # Set Source FIRST, before adding projections
    vg.Source = [body]
    page.addView(vg)
    doc.recompute()
    try:
        vg.ProjectionType = "Third Angle"
        vg.addProjection("Front")
        vg.addProjection("Top")
        vg.addProjection("Right")
        vg.ScaleType = "Automatic"
    except Exception as e:
        App.Console.PrintMessage("TechDraw setup issue: %s\\n" % e)
    doc.recompute()
    return page


def _auto_dimension(page, dims):
    """Add TechDraw dimensions for declared dim types.

    dims: list of dicts, each with at least {{"type": "od"|"height"|"pcd"|"id"}}
    plus optional {{"value": float}} for annotation (no measurement edge needed).

    Strategy: use LengthDimension anchored to bounding-box edges of the front view.
    Falls back to annotation-only dimension if edge selection fails.
    """
    try:
        import TechDraw
    except Exception:
        return
    if not page:
        return
    # Find the ProjGroup's Front view
    front = None
    for obj in doc.Objects:
        if obj.TypeId == "TechDraw::DrawProjGroupItem":
            try:
                if obj.Type == "Front":
                    front = obj
                    break
            except Exception:
                pass
    if front is None:
        # Try any view
        for obj in doc.Objects:
            if "DrawView" in obj.TypeId or "DrawProjGroup" in obj.TypeId:
                front = obj
                break
    if front is None:
        return

    for dim_spec in (dims or []):
        dtype = dim_spec.get("type", "")
        value = dim_spec.get("value")
        try:
            if dtype == "od":
                # Outer diameter → horizontal dimension spanning front view bbox
                dim = doc.addObject("TechDraw::DrawViewDimension", "Dim_OD")
                dim.Type = "DistanceX"
                dim.MeasureType = "True"
                if value:
                    dim.FormatSpec = "OD %(value).2f" % {{"value": value}}
            elif dtype == "id":
                dim = doc.addObject("TechDraw::DrawViewDimension", "Dim_ID")
                dim.Type = "DistanceX"
                if value:
                    dim.FormatSpec = "ID %(value).2f" % {{"value": value}}
            elif dtype == "height":
                dim = doc.addObject("TechDraw::DrawViewDimension", "Dim_H")
                dim.Type = "DistanceY"
                if value:
                    dim.FormatSpec = "H %(value).2f" % {{"value": value}}
            elif dtype == "pcd":
                # Pitch-circle diameter → radius dimension
                dim = doc.addObject("TechDraw::DrawViewDimension", "Dim_PCD")
                dim.Type = "Radius"
                if value:
                    dim.FormatSpec = "PCD %(value).2f" % {{"value": value}}
            else:
                continue
            # Attach to front view (edge selection is best-effort)
            try:
                dim.References2D = [(front, "Edge1")]
            except Exception:
                pass
            page.addView(dim)
            doc.recompute()
        except Exception as e:
            App.Console.PrintMessage("auto_dim skipped (%s): %s\\n" % (dtype, e))


# ------- BUILD FEATURES -------
'''


MACRO_EPILOGUE = '''
doc.recompute()

import os
_mp = __file__ if "__file__" in dir() else None
if _mp:
    fcstd = os.path.splitext(_mp)[0] + ".FCStd"
    doc.saveAs(fcstd)
    App.Console.PrintMessage("Saved: " + fcstd + "\\n")
else:
    App.Console.PrintMessage("Document built. Save manually.\\n")

try:
    import FreeCADGui
    FreeCADGui.SendMsgToActiveView("ViewFit")
    FreeCADGui.activeDocument().activeView().viewAxonometric()
except Exception:
    pass
'''


def emit(spec):
    part_name = spec.get("part_name", "Part")
    desc = spec.get("description", "")
    body_spec = spec["body"]

    out = MACRO_PREAMBLE.format(part_name=part_name, description=desc)
    out += "\n"

    # Datum planes (created before features, can be referenced as "datum:name")
    for dp in body_spec.get("datum_planes", []):
        out += (f'_make_datum_plane("{dp["name"]}", "{dp.get("ref", "XY")}", '
                f'offset_x={dp.get("offset_x", 0)}, offset_y={dp.get("offset_y", 0)}, '
                f'offset_z={dp.get("offset_z", 0)}, '
                f'rot_x={dp.get("rot_x", 0)}, rot_y={dp.get("rot_y", 0)}, '
                f'rot_z={dp.get("rot_z", 0)})\n')

    # Base
    base = body_spec["base"]
    base_name = base.get("name", "base")
    out += _emit_feature(base, base_name)

    # Features
    for i, f in enumerate(body_spec.get("features", []), start=1):
        fname = f.get("name", f"{f['type']}{i:03d}")
        out += _emit_feature(f, fname)

    # Drawing
    if spec.get("drawing"):
        out += "\n# ---- TechDraw page ----\n"
        out += "_make_techdraw()\n"

    out += MACRO_EPILOGUE
    return out


def _emit_feature(f, name):
    t = f["type"]
    lines = [f"\n# ---- {name} ({t}) ----"]
    sketch_var = f"sk_{_py_safe(name)}"
    feat_var = f"feat_{_py_safe(name)}"

    if t in ("Pad", "Pocket", "Revolution", "Hole"):
        sk = f["sketch"]
        geo = json.dumps(sk["geometry"])
        cons = json.dumps(sk.get("constraints", []))
        lines.append(f'{sketch_var} = _make_sketch("{sketch_var}", "{sk["plane"]}", {geo}, {cons})')

        if t == "Pad":
            lines.append(f'{feat_var} = _make_pad({sketch_var}, {f.get("length", 10)}, '
                         f'midplane={f.get("midplane", False)}, '
                         f'reversed={f.get("reversed", False)}, name="{name}")')
        elif t == "Pocket":
            lines.append(f'{feat_var} = _make_pocket({sketch_var}, {f.get("depth", 5)}, '
                         f'through_all={f.get("through_all", False)}, '
                         f'reversed={f.get("reversed", False)}, name="{name}")')
        elif t == "Revolution":
            lines.append(f'{feat_var} = _make_revolution({sketch_var}, "{f.get("axis","Z")}", '
                         f'angle={f.get("angle", 360)}, name="{name}")')
        elif t == "Hole":
            thread = f.get("thread", {})
            size = thread.get("size", "M4")
            threaded = thread.get("threaded", True)
            cb = f.get("counter_bore")
            cs = f.get("counter_sink")
            lines.append(f'{feat_var} = _make_hole({sketch_var}, "{size}", {f.get("depth", 10)}, '
                         f'threaded={threaded}, counter_bore={repr(cb)}, '
                         f'counter_sink={repr(cs)}, name="{name}")')

    elif t == "PolarPattern":
        srcs = ", ".join(f"feat_{_py_safe(s)}" for s in f["source_features"])
        lines.append(f'{feat_var} = _make_polar_pattern([{srcs}], '
                     f'"{f.get("axis","Z")}", {f.get("angle",360)}, '
                     f'{f.get("occurrences",4)}, name="{name}")')

    elif t == "LinearPattern":
        srcs = ", ".join(f"feat_{_py_safe(s)}" for s in f["source_features"])
        lines.append(f'{feat_var} = _make_linear_pattern([{srcs}], '
                     f'"{f.get("direction","X")}", {f.get("length",50)}, '
                     f'{f.get("occurrences",2)}, name="{name}")')

    elif t == "Mirrored":
        srcs = ", ".join(f"feat_{_py_safe(s)}" for s in f["source_features"])
        lines.append(f'{feat_var} = _make_mirrored([{srcs}], '
                     f'"{f.get("plane","XZ")}", name="{name}")')

    elif t == "Fillet":
        edges = json.dumps(f.get("edges", []))
        lines.append(f'{feat_var} = _make_fillet({edges}, {f.get("radius", 1)}, name="{name}")')

    elif t == "Chamfer":
        edges = json.dumps(f.get("edges", []))
        lines.append(f'{feat_var} = _make_chamfer({edges}, {f.get("size", 0.5)}, '
                     f'angle={f.get("angle", 45)}, name="{name}")')

    elif t == "radial_notch":
        # Radial slot: center-line points from origin at `angle` degrees.
        # Rectangle symmetric about that radial line, width in tangential direction,
        # extending from inner_r to outer_r (outer_r should exceed part OD to open the slot).
        import math as _math
        angle_deg = f.get("angle", 0)
        width = f.get("width", 10)
        inner_r = f.get("inner_r", 15)
        outer_r = f.get("outer_r", 50)
        depth = f.get("depth", 3)
        plane = f.get("plane", "face:top")
        ca = _math.cos(_math.radians(angle_deg))
        sa = _math.sin(_math.radians(angle_deg))
        hw = width / 2.0
        def _rot(r, yt):
            return [round(r * ca - yt * sa, 6), round(r * sa + yt * ca, 6)]
        pts = [
            _rot(inner_r, -hw),
            _rot(outer_r, -hw),
            _rot(outer_r, hw),
            _rot(inner_r, hw),
            _rot(inner_r, -hw),  # close
        ]
        sk_geom = [{"type": "polyline", "points": pts}]
        lines.append(f'{sketch_var} = _make_sketch("{sketch_var}", "{plane}", '
                     f'{json.dumps(sk_geom)}, [])')
        lines.append(f'{feat_var} = _make_pocket({sketch_var}, {depth}, name="{name}")')

    return "\n".join(lines) + "\n"


def _py_safe(s):
    import re
    return re.sub(r"\W", "_", s)


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    with open(sys.argv[1]) as f:
        spec = json.load(f)
    out_path = sys.argv[2]
    with open(out_path, "w") as f:
        f.write(emit(spec))
    print(f"Macro written: {out_path}")


if __name__ == "__main__":
    main()
